export const FETCH_ESTABLISHMENTS_START = 'ActionTypes.FETCH_ESTABLISHMENTS_START'
export const FETCH_ESTABLISHMENTS_END = 'ActionTypes.FETCH_ESTABLISHMENTS_END'
export const ESTABLISHMENTS_FETCHED = 'ActionTypes.ESTABLISHMENTS_FETCHED'

export const FETCH_BEERS_START = 'ActionTypes.FETCH_BEERS_START'
export const FETCH_BEERS_END = 'ActionTypes.FETCH_BEERS_END'
export const BEERS_FETCHED = 'ActionTypes.BEERS_FETCHED'
